In [ ]:
import pandas as pd
import json
import numpy  as np
import os
import re
import copy
from sklearn.metrics                  import classification_report
from sklearn.feature_extraction.text  import TfidfVectorizer
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score

In [ ]:
train = pd.read_csv('/content/drive/MyDrive/NLP/csvfiles/taskb/trainingData.csv')

In [ ]:
train

text                  id  \
0    France: 10 people dead after shooting at HQ of...  552783667052167168   
1    BREAKING: 10 reportedly shot dead at Paris HQ ...  552785375161499649   
2    BREAKING: At least 10 killed in shooting at Fr...  552791196247269378   
3    Eleven dead in shooting at Paris offices of sa...  552791578893619200   
4    BREAKING Charlie Hebdo latest: 11 dead 10 woun...  552792544132997121   
..                                                 ...                 ...   
321  [Serious] Is it true that 85% of people can on...              8gp0d7   
322  Did Eric Schneiderman Help NXIVM Sell Child Se...              8i274x   
323       Debunk this: The direction you sleep matters              8n9173   
324  Is it true police officers must hit a quota at...              8unvgg   
325  Jon Sopel: Bizarre. $MENTION$ says he came to ...              8yktu5   

     label  labelvalue  
0     true           0  
1     true           0  
2     true           0  
3     true           0  
4     true           0  
..     ...         ...  
321   true           0  
322  false           1  
323  false           1  
324  false           1  
325  false           1  

[326 rows x 4 columns]

In [ ]:
test = pd.read_csv('/content/drive/MyDrive/NLP/csvfiles/taskb/testData.csv')

In [ ]:
test

text                  id  \
0   #Breaking: Pentagon releases video of the “mot...  852844529778601985   
1   Rep. Sheila Jackson Lee has no shame. I still ...  443938194715713536   
2   ICYMI: "Rep Sheila Jackson Lee (D-Tx) Wants Hu...  774165935041093633   
3   In 2003, Houston U.S. Rep. Sheila Jackson Lee ...  909084965035487232   
4   Noah’s Ark Theme Park Destroyed in a Flood? $URL$  897502435593265152   
..                                                ...                 ...   
76  People who can't smell. Is it true that there ...              8m9y0o   
77  Great Pyramid of Giza can focus electromagneti...              938o5h   
78  Is it true that the federal government require...               ayn70   
79        Is it true Romney has Caymen bank accounts?               wfajw   
80  I've been searching, and can't find a single c...               xn2bn   

    label  labelvalue  
0   false           1  
1    true           0  
2    true           0  
3    true           0  
4   false           1  
..    ...         ...  
76   true           0  
77   true           0  
78  false           1  
79   true           0  
80  false           1  

[81 rows x 4 columns]

In [ ]:
train['label'].isnull().sum()

0

In [ ]:
x_train = train['text'].tolist()
y = train['labelvalue'].fillna(0)
y_train = y.tolist()



x_test = test['text'].tolist()
y_test = test['labelvalue'].tolist()

#Instantiating TfidfVectorizer object and fitting it on the training set
tfidf         = TfidfVectorizer(min_df = 10, max_df = 0.5, ngram_range=(1,2))
x_train_feats = tfidf.fit(x_train)




TfidfVectorizer(max_df=0.5, min_df=10, ngram_range=(1, 2))
102
(326, 102)


In [ ]:
SVM = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='auto',probability=True)
SVM.fit(x_train_transform,y_train)
# predict the labels on validation dataset
predictions_SVM = SVM.predict(x_test)
# Use accuracy_score function to get the accuracy
print("SVM Accuracy Score -> ",accuracy_score(predictions_SVM, y_test)*100)

SVM Accuracy Score ->  41.9753086419753


In [ ]:
class_probabilities = SVM.predict_proba(x_test)

In [ ]:
predictions_SVM

array([0, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 0, 1, 2, 1, 0, 0, 0, 0, 0, 2, 0,
       0, 0, 0, 2, 2, 2, 1, 0, 0, 0, 2, 2, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 2, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 2])

In [ ]:
class_probabilities

array([[0.52855302, 0.09245462, 0.37899236],
       [0.46685654, 0.30519835, 0.22794511],
       [0.42295983, 0.21115118, 0.36588898],
       [0.42063093, 0.12052115, 0.45884792],
       [0.3885192 , 0.21025406, 0.40122674],
       [0.25492315, 0.3344264 , 0.41065045],
       [0.32668543, 0.27382531, 0.39948926],
       [0.31694369, 0.14902207, 0.53403424],
       [0.46727399, 0.24328312, 0.28944288],
       [0.3613709 , 0.12490136, 0.51372773],
       [0.3613709 , 0.12490136, 0.51372773],
       [0.67150134, 0.0624591 , 0.26603956],
       [0.32094351, 0.58668494, 0.09237155],
       [0.12795589, 0.35173051, 0.5203136 ],
       [0.30322968, 0.45475187, 0.24201845],
       [0.3741752 , 0.18158821, 0.44423658],
       [0.33914676, 0.29175529, 0.36909795],
       [0.35091225, 0.2681113 , 0.38097644],
       [0.35091225, 0.2681113 , 0.38097644],
       [0.35091225, 0.2681113 , 0.38097644],
       [0.28449587, 0.29057229, 0.42493184],
       [0.40754032, 0.2807799 , 0.31167978],
       [0.

In [ ]:
class_probabilities[1][predictions_SVM[1]]

0.46084108406461416

In [ ]:
predictions_SVM

array([0, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 0, 1, 2, 1, 0, 0, 0, 0, 0, 2, 0,
       0, 0, 0, 2, 2, 2, 1, 0, 0, 0, 2, 2, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 2, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 2])

In [ ]:
cscore = []
for i in range(len(predictions_SVM)):
  if predictions_SVM[i] == 2:
    cscore.append(0)
  else:
    cscore.append(class_probabilities[i][predictions_SVM[i]])

In [ ]:
oneList = [1]*len(cscore)

In [ ]:
from sklearn.metrics import mean_squared_error

rms = mean_squared_error(oneList,cscore, squared=False)


In [ ]:
rms

0.6243523195029409

In [ ]:
cr = classification_report(y_test, predictions_SVM)
print(cr)

              precision    recall  f1-score   support

           0       0.44      0.52      0.48        31
           1       0.57      0.42      0.49        40
           2       0.07      0.10      0.08        10

    accuracy                           0.42        81
   macro avg       0.36      0.35      0.35        81
weighted avg       0.46      0.42      0.43        81



In [ ]:
from sklearn.neural_network import MLPClassifier

In [ ]:
clf = MLPClassifier(random_state=1, max_iter=300).fit(x_train_transform,y_train)
preds = clf.predict(x_test)
print("mlp Accuracy Score -> ",accuracy_score(preds, y_test)*100)

mlp Accuracy Score ->  43.20987654320987


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [ ]:
cr = classification_report(y_test, preds)
print(cr)

              precision    recall  f1-score   support

           0       0.42      0.26      0.32        31
           1       0.62      0.62      0.62        40
           2       0.09      0.20      0.13        10

    accuracy                           0.43        81
   macro avg       0.38      0.36      0.36        81
weighted avg       0.48      0.43      0.45        81



In [ ]:
preds

array([0, 0, 2, 2, 1, 2, 0, 2, 0, 2, 2, 0, 1, 2, 1, 2, 1, 0, 0, 0, 2, 1,
       0, 1, 1, 2, 2, 2, 1, 0, 0, 0, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 0, 0, 1, 1, 1, 1, 0, 1, 2, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 2, 1, 1, 0, 2, 1, 1, 2])

In [ ]:
c=0
p = list(preds)
for i in range(len(preds)):
  if preds[i] == y_test[i]:
    c +=1
    print(preds[i],y_test[i])
print(c)

0 0
1 1
0 0
0 0
1 1
2 2
0 0
1 1
0 0
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
0 0
1 1
1 1
1 1
0 0
1 1
1 1
1 1
2 2
0 0
1 1
35


In [ ]:
class_probabilities = clf.predict_proba(x_test)

In [ ]:
class_probabilities

array([[9.34323828e-01, 1.10418157e-04, 6.55657539e-02],
       [8.66090697e-01, 1.31241095e-01, 2.66820801e-03],
       [6.68133262e-02, 3.27274476e-02, 9.00459226e-01],
       [2.73136407e-01, 3.03483432e-02, 6.96515250e-01],
       [2.79738818e-01, 3.62691635e-01, 3.57569546e-01],
       [1.92912564e-01, 2.19902877e-01, 5.87184559e-01],
       [6.20666466e-01, 9.95699744e-02, 2.79763560e-01],
       [3.24741017e-02, 8.62065960e-04, 9.66663832e-01],
       [7.52054765e-01, 2.08112785e-01, 3.98324501e-02],
       [1.56026433e-01, 3.06458428e-03, 8.40908983e-01],
       [1.56026433e-01, 3.06458428e-03, 8.40908983e-01],
       [7.57639885e-01, 4.76968763e-04, 2.41883146e-01],
       [2.95772838e-03, 9.96960905e-01, 8.13665233e-05],
       [6.25872661e-04, 2.12890118e-01, 7.86484009e-01],
       [1.51051880e-02, 9.80444459e-01, 4.45035252e-03],
       [1.16806391e-01, 3.37153434e-01, 5.46040175e-01],
       [5.70329649e-02, 7.89697304e-01, 1.53269731e-01],
       [4.89525956e-01, 4.03107

In [ ]:
cscoreMLP = []
for i in range(len(preds)):
  if preds[i] == 2:
    cscoreMLP.append(0)
  else:
    cscoreMLP.append(class_probabilities[i][preds[i]])

In [ ]:
cscoreMLP

[0.9343238279646502,
 0.8660906965308149,
 0,
 0,
 0.3626916353173756,
 0,
 0.6206664658349468,
 0,
 0.752054764625087,
 0,
 0,
 0.7576398854361921,
 0.9969609050957294,
 0,
 0.9804444594470706,
 0,
 0.7896973042482119,
 0.48952595606931554,
 0.48952595606931554,
 0.48952595606931554,
 0,
 0.5682853942186564,
 0.3869781009676343,
 0.5744613043973454,
 0.5744613043973454,
 0,
 0,
 0,
 0.9936054036775154,
 0.9620545397318523,
 0.9620545397318523,
 0.7421773937989014,
 0,
 0,
 0.9974761764695358,
 0.9769789560275509,
 0.9993751388790669,
 0.9968461053546048,
 0.9998022641796498,
 0.9998022641796498,
 0.42895104653560157,
 0.7207082808116302,
 0.8743056074158722,
 0.9821555675436862,
 0,
 0.9997105822981628,
 0.9997105822981628,
 0.9988374575757588,
 0.9993696155108155,
 0.6842605354640628,
 0,
 0.5744613043973454,
 0,
 0,
 0.9890190980582088,
 0.7234572912875762,
 0.5810099952915009,
 0.9963026920085197,
 0.43512545792435,
 0.958819599899386,
 0.7209312857888913,
 0.8302849692622418,
 0.9

In [ ]:
oneList = [1]*len(cscoreMLP)

In [ ]:
from sklearn.metrics import mean_squared_error

rmsMLP = mean_squared_error(oneList,cscoreMLP, squared=False)


In [ ]:
rmsMLP

0.5712503086670723