In [61]:
import pandas as pd

In [62]:
data = pd.read_csv('/content/drive/MyDrive/NLP/csvfiles/dataFile.csv')

In [63]:
data = data.drop('Unnamed: 0',axis=1)

In [64]:
y_train = data['label_b']

In [65]:
data

type                  id  \
0    source  529660296080916480   
1    source  529653029747064832   
2    source  529687410611728384   
3    source  529713467184676864   
4    source  529689679411810304   
..      ...                 ...   
360  source              6hb6b3   
361  source              7d28gk   
362  source              83ddtk   
363  source              8j9s33   
364  source              934q6t   

                                                  text   ups  label_a  label_b  
0    Prince is playing a secret show in Toronto ton...    47        0      0.0  
1    Prince fans lining up at Massey Hall. Wristban...     7        0      0.0  
2    Is it true? Prince rumoured to be performing s...     8        3      0.0  
3    Secret Prince show rumored for Toronto tonight...    37        0      0.0  
4    People talking about stupid shit like governme...     5        0      0.0  
..                                                 ...   ...      ...      ...  
360  Is it true the Earth is flat? Is there proof? ...     0        1      1.0  
361  Is it true that some people in America gets ja...     0        1      0.0  
362  Oh sweet and wholesome Reddit, is it true US c...     0        1      2.0  
363  Face facts: Immigrants commit fewer crimes tha...  1442        0      0.0  
364  Iodine increases IQ and is an essential part o...   196        0      1.0  

[365 rows x 6 columns]

In [66]:
X_train = pd.DataFrame()

In [67]:

X_train['ups'] = data['ups']
X_train['label_a'] = data['label_a']
X_train['text'] = data['text']

In [68]:
X_train

ups  label_a                                               text
0      47        0  Prince is playing a secret show in Toronto ton...
1       7        0  Prince fans lining up at Massey Hall. Wristban...
2       8        3  Is it true? Prince rumoured to be performing s...
3      37        0  Secret Prince show rumored for Toronto tonight...
4       5        0  People talking about stupid shit like governme...
..    ...      ...                                                ...
360     0        1  Is it true the Earth is flat? Is there proof? ...
361     0        1  Is it true that some people in America gets ja...
362     0        1  Oh sweet and wholesome Reddit, is it true US c...
363  1442        0  Face facts: Immigrants commit fewer crimes tha...
364   196        0  Iodine increases IQ and is an essential part o...

[365 rows x 3 columns]

In [69]:
y_train = data['label_b'].astype(int)

In [70]:
X_train = X_train.to_numpy()
X_train

array([[47, 0,
        'Prince is playing a secret show in Toronto tonight. I will also be playing a secret show tonight involving pizza &amp; netflix bingeing.'],
       [7, 0,
        'Prince fans lining up at Massey Hall. Wristbands for surprise show reportedly on sale at $NUMBER$pm. $HASHTAG$ $URL$'],
       [8, 3,
        'Is it true? Prince rumoured to be performing surprise show in Toronto $URL$'],
       ...,
       [0, 1,
        'Oh sweet and wholesome Reddit, is it true US citizens have to pay to use US dollar bills as currency?'],
       [1442, 0,
        'Face facts: Immigrants commit fewer crimes than U.S.-born peers'],
       [196, 0,
        'Iodine increases IQ and is an essential part of the human diet, yet is absent from almost all salts today.']],
      dtype=object)

In [71]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( X_train, y_train, test_size=0.20, random_state=42)

In [72]:
x_train

array([[33, 0,
        'SYDNEY HOSTAGE-TAKER - Man Monis, $NUMBER$ - Originally from Iran - Self-styled sheikh - Accused of sexually assaulting $NUMBER$ women DEVELOPING..'],
       [1, 1,
        'Is it true that when you shave hair on a certain part of your body it grows back thicker?'],
       [32, 0,
        'Sydney Opera House evacuated, concourse deserted $URL$ $HASHTAG$ (via $MENTION$) $URL$'],
       [2123, 0,
        'Anyone who knows Marina Joyce personally knows she has a serious drug addiction. she needs help, but in the form of rehab $HASHTAG$'],
       [94, 0,
        'Heart goes out to $NUMBER$ passengers and crew of Germanwings Airbus A320 that has crashed in French Alps, Southern France $URL$'],
       [3, 1,
        'Is it true police officers must hit a quota at the end of every month? Why?'],
       [28, 0,
        'BREAKING NEWS: Soldier shot at National War Memorial in Ottawa $URL$'],
       [80, 0,
        '$HASHTAG$ news: Shots fired at Parliament Hill. Follow d

In [73]:
from sklearn.neural_network import MLPClassifier

In [74]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline, FeatureUnion

from sklearn.preprocessing import FunctionTransformer


# Create Function Transformer to use Feature Union
def get_numeric_data(x):
   # print([record[:-1].astype(float) for record in x])
    return [record[:-1].astype(float) for record in x]

def get_text_data(x):
    return [record[2] for record in x]

transfomer_numeric = FunctionTransformer(get_numeric_data)
transformer_text = FunctionTransformer(get_text_data)

# Create a pipeline to concatenate Tfidf Vector and Numeric data

pipeline = Pipeline([
    ('features', FeatureUnion([
            ('numeric_features', Pipeline([
                ('selector', transfomer_numeric)
            ])),
             ('text_features', Pipeline([
                ('selector', transformer_text),
                ('vec', TfidfVectorizer(analyzer='word'))
            ]))
         ])),
    ('clf',MLPClassifier(random_state=1, max_iter=300))
])



pipeline.fit(x_train, y_train)


Pipeline(steps=[('features',
                 FeatureUnion(transformer_list=[('numeric_features',
                                                 Pipeline(steps=[('selector',
                                                                  FunctionTransformer(func=<function get_numeric_data at 0x7f851af8dc20>))])),
                                                ('text_features',
                                                 Pipeline(steps=[('selector',
                                                                  FunctionTransformer(func=<function get_text_data at 0x7f851b0365f0>)),
                                                                 ('vec',
                                                                  TfidfVectorizer())]))])),
                ('clf', MLPClassifier(max_iter=300, random_state=1))])

In [75]:
predictions = pipeline.predict(x_test)

In [76]:
predictions

array([1, 0, 1, 2, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 2, 2, 0, 2, 0, 0, 0, 2,
       1, 0, 0, 2, 1, 2, 2, 1, 1, 1, 0, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 2, 0, 1, 0, 0, 0, 1, 1, 2, 2, 1, 1,
       1, 1, 1, 0, 0, 2, 1])

In [77]:
from sklearn.metrics import accuracy_score
print("Accuracy Score -> ",accuracy_score(predictions, y_test)*100)

Accuracy Score ->  58.9041095890411


In [78]:
from sklearn.metrics                  import classification_report

In [79]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.50      0.55      0.52        20
           1       0.68      0.72      0.70        32
           2       0.53      0.43      0.47        21

    accuracy                           0.59        73
   macro avg       0.57      0.57      0.56        73
weighted avg       0.59      0.59      0.59        73



In [80]:
class_probabilities = pipeline.predict_proba(x_test)

In [81]:
class_probabilities

array([[7.58172646e-02, 7.65441197e-01, 1.58741539e-01],
       [4.06989684e-01, 3.69740402e-01, 2.23269914e-01],
       [4.68251821e-02, 5.62878918e-01, 3.90295900e-01],
       [2.93901571e-02, 8.79801052e-03, 9.61811832e-01],
       [4.72282544e-01, 4.71279113e-01, 5.64383430e-02],
       [5.68504148e-01, 2.86994126e-01, 1.44501725e-01],
       [4.52814556e-01, 2.62086804e-01, 2.85098640e-01],
       [6.70401798e-02, 7.79075549e-01, 1.53884272e-01],
       [9.24577875e-02, 6.73493056e-01, 2.34049156e-01],
       [2.34476118e-03, 9.85190891e-01, 1.24643482e-02],
       [1.55447092e-01, 6.06581522e-01, 2.37971386e-01],
       [2.32299098e-02, 9.60455555e-01, 1.63145349e-02],
       [6.23526022e-01, 1.08919054e-01, 2.67554925e-01],
       [1.01413573e-01, 7.89429400e-01, 1.09157027e-01],
       [3.28578200e-01, 1.10651084e-02, 6.60356692e-01],
       [1.24277892e-01, 2.02644185e-01, 6.73077923e-01],
       [9.75180432e-01, 1.28470950e-02, 1.19724733e-02],
       [4.15828582e-02, 8.28345

In [82]:
cscoreMLP = []
for i in range(len(predictions)):

    cscoreMLP.append(class_probabilities[i][predictions[i]])

In [83]:
cscoreMLP

[0.7654411968319575,
 0.40698968399814384,
 0.5628789175185852,
 0.9618118323301053,
 0.47228254403967856,
 0.5685041483342776,
 0.4528145560305434,
 0.7790755487004437,
 0.6734930560223201,
 0.9851908906001395,
 0.6065815217803295,
 0.9604555552867396,
 0.6235260215595565,
 0.7894293999412281,
 0.6603566916828396,
 0.673077923468071,
 0.9751804316775461,
 0.9501336837124763,
 0.810611865119822,
 0.9149996197777196,
 0.8332030848226913,
 0.5841944400693684,
 0.564235172882103,
 0.5226425144343125,
 0.6347597368426381,
 0.6730840024284871,
 0.7092165352102532,
 0.947181437081097,
 0.8493354543642243,
 0.8816372661887245,
 0.9106974606185249,
 0.7672768354024082,
 0.9795728254918818,
 0.5994214504068133,
 0.8027879135453312,
 0.7520644201122776,
 0.8744843254550086,
 0.5102495435298302,
 0.4468818350051577,
 0.7015277522098763,
 0.8514752963189459,
 0.49745279993523583,
 0.6196607637156978,
 0.8644429007293603,
 0.880287573488981,
 0.4956942430496761,
 0.4313218530663824,
 0.901623592022

In [84]:
oneList = [1]*len(cscoreMLP)

In [85]:
from sklearn.metrics import mean_squared_error

rmsMLP = mean_squared_error(oneList,cscoreMLP, squared=False)

In [86]:
rmsMLP

0.31784721044130565