In [1]:
import keras
import tensorflow

import numpy as np
import pandas as pd


from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils.np_utils import to_categorical

from keras.layers import Embedding
from keras.layers import Dense, Input, Flatten
from keras.layers import Conv1D, MaxPooling1D, Dropout
from keras.models import Model

from keras.models import Sequential

from tensorflow.keras.layers import BatchNormalization

from keras.layers import LSTM


In [2]:


MAX_SEQUENCE_LENGTH = 512
MAX_NB_WORDS = 2000
EMBEDDING_DIM = 100


data_train = pd.read_csv('/content/drive/MyDrive/NLP/csvfiles/dataFile.csv')

In [3]:
data_train = data_train.drop('Unnamed: 0',axis=1)

In [4]:
data_train

type                  id  \
0    source  529660296080916480   
1    source  529653029747064832   
2    source  529687410611728384   
3    source  529713467184676864   
4    source  529689679411810304   
..      ...                 ...   
360  source              6hb6b3   
361  source              7d28gk   
362  source              83ddtk   
363  source              8j9s33   
364  source              934q6t   

                                                  text   ups  label_a  label_b  
0    Prince is playing a secret show in Toronto ton...    47        0      0.0  
1    Prince fans lining up at Massey Hall. Wristban...     7        0      0.0  
2    Is it true? Prince rumoured to be performing s...     8        3      0.0  
3    Secret Prince show rumored for Toronto tonight...    37        0      0.0  
4    People talking about stupid shit like governme...     5        0      0.0  
..                                                 ...   ...      ...      ...  
360  Is it true the Earth is flat? Is there proof? ...     0        1      1.0  
361  Is it true that some people in America gets ja...     0        1      0.0  
362  Oh sweet and wholesome Reddit, is it true US c...     0        1      2.0  
363  Face facts: Immigrants commit fewer crimes tha...  1442        0      0.0  
364  Iodine increases IQ and is an essential part o...   196        0      1.0  

[365 rows x 6 columns]

In [5]:

texts = []
labels = []

for i in range(data_train.text.shape[0]):
   
        texts.append(str(data_train.text[i]))
        labels.append(data_train.label_b[i])

In [6]:
tokenizer = Tokenizer(num_words=MAX_NB_WORDS)
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)

word_index = tokenizer.word_index

data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)
labels = to_categorical(np.asarray(labels),num_classes = 3)


Found 1665 unique tokens.
Shape of data tensor: (365, 512)
Shape of label tensor: (365, 3)


In [9]:
labels

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]], dtype=float32)

In [10]:
indices = np.arange(data.shape[0])
np.random.shuffle(indices)

x_train, x_test, y_train, y_test = train_test_split( data[indices], labels[indices], test_size=0.20, random_state=1)


In [ ]:
y_train

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0

In [11]:

embeddings_index = {}
with open('/content/drive/MyDrive/NLP/test/testsam/glove.6B.100d.txt') as f:
    for line in f:
        word = line.split()[0]
        coefs = np.asarray(line.split()[1:], dtype='float32')
        embeddings_index[word] = coefs

print('Total %s word vectors in Glove.' % len(embeddings_index))



Total 400000 word vectors in Glove.


In [ ]:
embedding_matrix = np.random.random((len(word_index) + 1, EMBEDDING_DIM))
for w, i in word_index.items():
    embedding_vector = embeddings_index.get(w)
    if embedding_vector is not None: 
        embedding_matrix[i] = embedding_vector

In [12]:
x_train

array([[   0,    0,    0, ...,  133, 1376,    1],
       [   0,    0,    0, ...,   17,   92,    2],
       [   0,    0,    0, ..., 1360, 1361,    1],
       ...,
       [   0,    0,    0, ...,   14,    2,    1],
       [   0,    0,    0, ...,    7,  174,    2],
       [   0,    0,    0, ...,    5,  270,    2]], dtype=int32)

In [31]:
[row[-2] for row in X_train1]

[47,
 7,
 8,
 37,
 5,
 1,
 9,
 4,
 8,
 7,
 5,
 49,
 70,
 101,
 7,
 19,
 28,
 54,
 181,
 60,
 89,
 416,
 41,
 73,
 97,
 17,
 279,
 187,
 331,
 85,
 21,
 127,
 6,
 13,
 224,
 20,
 58,
 118,
 130,
 56,
 201,
 250,
 247,
 68,
 20,
 10,
 35,
 20,
 13,
 54,
 14,
 194,
 145,
 30,
 134,
 11,
 36,
 65,
 66,
 144,
 232,
 351,
 23,
 20,
 129,
 28,
 80,
 80,
 12,
 312,
 32,
 10,
 45,
 24,
 94,
 2123,
 97,
 153,
 34,
 1114,
 189,
 462,
 1635,
 62,
 94,
 9,
 3,
 42,
 33,
 21,
 10,
 4,
 53,
 32,
 523,
 5,
 202,
 39,
 684,
 14,
 10,
 17,
 10,
 22,
 17,
 497,
 15,
 5,
 1,
 17,
 8,
 7,
 85,
 328,
 50,
 98,
 5,
 41,
 55,
 43,
 57,
 142,
 64,
 91,
 18,
 171,
 28,
 19,
 20,
 69,
 28,
 215,
 601,
 38,
 40,
 108,
 41,
 192,
 37,
 39,
 40,
 17,
 27,
 572,
 33,
 160,
 25,
 27,
 65,
 63,
 24,
 53,
 42,
 58,
 22,
 78,
 23,
 30,
 19,
 596,
 31,
 28,
 698,
 69,
 28,
 44,
 11,
 17,
 28,
 21,
 38,
 119,
 31,
 18,
 84,
 32,
 33,
 268,
 38,
 38,
 131,
 27,
 17,
 43,
 32,
 318,
 18,
 183,
 78,
 28,
 123,
 14,
 69,
 20,

In [ ]:
embedding_layer = Embedding(len(word_index) + 1, EMBEDDING_DIM, weights=[embedding_matrix], input_length=MAX_SEQUENCE_LENGTH)

embedding_vecor_length = 32
model = Sequential()
model.add(embedding_layer)
model.add(Dropout(0.2))
model.add(Conv1D(filters=32, kernel_size=5, padding='same', activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(Conv1D(filters=64, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2))
model.add(BatchNormalization())
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())
model.fit(x_train, y_train, epochs=50, batch_size=128)

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 1000, 100)         166600    
                                                                 
 dropout_2 (Dropout)         (None, 1000, 100)         0         
                                                                 
 conv1d_4 (Conv1D)           (None, 1000, 32)          16032     
                                                                 
 max_pooling1d_4 (MaxPooling  (None, 500, 32)          0         
 1D)                                                             
                                                                 
 conv1d_5 (Conv1D)           (None, 500, 64)           6208      
                                                                 
 max_pooling1d_5 (MaxPooling  (None, 250, 64)          0         
 1D)                                                  

In [ ]:
correct_predictions = 0
preds = []
actual = []



In [ ]:
test_preds = model.predict(x_test)

for i in range(len(test_preds)):
    preds.append(np.argmax(test_preds[i]))
    actual.append(np.argmax(y_test[i]))
    if np.argmax(test_preds[i])==np.argmax(y_test[i]):
        correct_predictions+=1
print("Correct predictions:", correct_predictions)
print("Total number of test examples:", len(y_test))
print("Accuracy of model: ", correct_predictions/float(len(y_test)))

Correct predictions: 36
Total number of test examples: 73
Accuracy of model:  0.4931506849315068


In [ ]:
from sklearn.metrics import f1_score

In [ ]:
f1_score(actual,preds, average='macro')

0.4237396590337767

In [ ]:
cscoreMLP = []
for i in range(len(preds)):
    cscoreMLP.append(test_preds[i][preds[i]])

In [ ]:
oneList = [1]*len(cscoreMLP)

In [ ]:
from sklearn.metrics import mean_squared_error

rmsMLP = mean_squared_error(oneList,cscoreMLP, squared=False)

In [ ]:
rmsMLP

0.23519540980543643

In [ ]:
preds

[1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1]